---
# tasks file for rsyslog (Debian)

- name: Install rsyslog packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ rsyslog_packages }}"
  tags:
    - rsyslog
