---
# tasks file for rsyslog

- name: Include distribution specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - rsyslog

- include: RedHat.yml
  when: ansible_os_family == "RedHat"
  tags:
    - rsyslog

- include: Debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - rsyslog

- set_fact:
    rainerscript: "{{ (ansible_distribution_release == 'xenial' or (ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0]|int >= 7)) }}"

- name: Create rsyslog.conf configuration file
  become: yes
  template:
    src: "{{ 'rainer_' if rainerscript|bool else '' }}rsyslog.conf.j2"
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart rsyslog
  tags:
    - rsyslog

- name: Create rsyslog.d configuration directory
  become: yes
  file:
    path: /etc/rsyslog.d
    owner: root
    group: root
    mode: 0755
    state: directory
  tags:
    - rsyslog

- name: Ensure listen file is not present in rsyslog.d configuration directory
  become: yes
  file:
    path: /etc/rsyslog.d/listen.conf
    state: absent
  notify:
    - restart rsyslog
  tags:
    - rsyslog

- name: Create rsyslog work directory
  become: yes
  file:
    path: "{{ rsyslog_work_directory }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  tags:
    - rsyslog

- name: Create rsyslog default configuration file
  become: yes
  template:
    src: 50-default.conf.j2
    dest: /etc/rsyslog.d/50-default.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart rsyslog
  tags:
    - rsyslog

- name: Create application specific configuration files
  become: yes
  template:
    src: app.conf.j2
    dest: /etc/rsyslog.d/{{ item.priority }}-{{ item.name }}.conf
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ rsyslog_apps }}"
  notify:
    - restart rsyslog
  tags:
    - rsyslog

- name: Create application specific rb files
  become: yes
  template:
    src: app.rb.j2
    dest: /etc/rsyslog.d/{{ item.name }}.rb
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ rsyslog_rulebase|d([]) }}"
  notify:
    - restart rsyslog
  tags:
    - rsyslog

- name: Ensure rsyslog Unit file requires network
  lineinfile:
    path: "{{ rsyslog_unit }}"
    regexp: '^Wants=network.target'
    insertafter: '^Description='
    line: 'Wants=network.target'    
  when: rsyslog_network|d(false)
  notify:
    - restart rsyslog

- name: Ensure rsyslog service is started and enabled on boot
  become: yes
  service:
    name: "{{ rsyslog_service_name }}"
    state: started
    enabled: yes
  tags:
    - rsyslog
