---
# tasks file for rsyslog (CentOS specific)
- name: Add Rsyslog Repository
  yum_repository:
    name: rsyslog_v8
    description: Adiscon CentOS Rsyslog
    baseurl: http://rpms.adiscon.com/v8-stable/epel-$releasever/$basearch
    gpgkey: http://rpms.adiscon.com/RPM-GPG-KEY-Adiscon
    gpgcheck: yes

- name: Install rsyslog packages
  become: yes
  yum:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - "{{ rsyslog_packages }}"
  tags:
    - rsyslog

- name: Install rsyslog-relp packages
  become: yes
  yum:
    name: "{{ rsyslog_packages|map('regex_replace','^(rsyslog)(-\\d*.*)?$','\\1-relp\\2')|first }}"
    state: installed
    update_cache: no
  when: rsyslog_packages|map('regex_replace','^(rsyslog-relp).*$','\\1')|select('equalto','rsyslog-relp')|list|length == 0
  tags:
    - rsyslog

- name: Install rsyslog-mmnormalize packages
  become: yes
  yum:
    name: "{{ rsyslog_packages|map('regex_replace','^(rsyslog)(-\\d*.*)?$','\\1-mmnormalize\\2')|first }}"
    state: installed
    update_cache: no
  when: 
  - rsyslog_packages|map('regex_replace','^(rsyslog-mmnormalize).*$','\\1')|select('equalto','rsyslog-mmnormalize')|list|length == 0
  - rsyslog_modules|selectattr("type","equalto","omrelp")
  tags:
    - rsyslog
